baseURL = "https://github.com/sohanrai09/blog/"
languageCode = "en-us"
title = "Sohan”’s blog
theme = "hugo-book"

[params]
  author = "Sohan” Rai
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/sohanrai09"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/SohanRai23"
